wandb_version: 1

decay:
  desc: null
  value: 1.0e-07
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 27
hidden_layer_size:
  desc: null
  value: 128
layer_1_size:
  desc: null
  value: 18
layer_2_size:
  desc: null
  value: 28
learn_rate:
  desc: null
  value: 0.003
momentum:
  desc: null
  value: 0.95
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704490416.395668
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      - 37
      4: 3.11.5
      5: 0.16.1
      8:
      - 4
      - 5
      13: darwin-arm64
