wandb_version: 1

decay:
  value: 1.0e-05
dropout:
  value: 0.4
epochs:
  value: 27
hidden_layer_size:
  value: 148
layer_1_size:
  value: 10
layer_2_size:
  value: 36
learn_rate:
  value: 0.001
momentum:
  value: 0.95
